import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import images from "@/asset";
import { delay, motion } from "framer-motion";
import { useState } from "react";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Servings from "@/components/Servings";
import Shop from "@/components/Shop";
import VarietyPack from "@/components/VarietyPack";
import Philosophy from "@/components/Philosophy";
import Footer from "@/components/Footer";
import Decoration from "@/components/Decoration";

const inter = Inter({ subsets: ["latin"] });

const Ab = ({ children }) => {
    return (
        <motion.div
            initial={{ opacity: 0, scale: 0, y: 0 }}
            whileInView={{ opacity: 1, scale: 1, y: [200, 0] }}
            viewport={{ once: true }}
        >
            {children}
        </motion.div>
    );
};

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossorigin
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                    rel="stylesheet"
                />
            </Head>

            <main>
                <Decoration />

                <Navbar />

                <Header />

                <div className="gradient"></div>

                <Servings />

                <Shop />

                <VarietyPack />

                <div className="margin_green"></div>

                <Philosophy />

                <Footer />
            </main>
        </>
    );
}
