import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import images from "@/asset";
import { motion } from "framer-motion";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [firstHover, setFirstHover] = useState(false);
  const [secondHover, setSecondHover] = useState(false);
  const [thirdHover, setThirdHover] = useState(false);

  console.log(firstHover)


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <div className="header">
          <nav>
            <button className="shop">Shop</button>
            <button className="meet">Meet Smoothe</button>
            <div className="logo">Smoothe</div>
            <div className="margin"></div>
            <div className="kart">kart</div>
          </nav>
          <div className="header-content">
            <div className="header-left">
              <h1>A Better Smoothie is Here</h1>
              <h2>Delicious smoothies without any of the prep. Made with real fruits & veggies plus plant protein!</h2>
              <motion.button
              whileHover={{scale: 1.1}}
              >Shop Now </motion.button>
            </div>
            <div className="header-right">
              <div className="header-image">
                <motion.div 
                initial={{scale: 0.9, x: 170, y: 20, rotate: '16deg'}}   
                animate={{y:[0, 20, 0]}}
                transition={{duration: 6, repeat: Infinity, ease: 'easeInOut'}}
                className="image-1">
                  <Image src={images.Smoothe1} />
                </motion.div>
                <motion.div 
                initial={{scale: 0.95, x: -170, y: -20, rotate: '-12deg'}}       
                animate={{y:[-20, 0, -20], x:[-180, -170, -180], rotate:['-12deg', '-10deg', '-12deg']}}
                transition={{duration: 6, repeat: Infinity, type: "easeInOut"}}         
                className="image-2">
                  <Image src={images.Smoothe2} />
                </motion.div>
                <motion.div     
                animate={{y:[0, -20, 0], rotate:['0deg', '2deg', '0deg']}}
                transition={{duration: 6, repeat: Infinity, type: "easeInOut"}}                    
                className="image-3">
                  <Image src={images.Smoothe3} />
                </motion.div>
              </div>
            </div>
          </div>
        </div>

        <div className="gradient"></div>

        <div className="second-sec">

          <div
          onMouseEnter={() => {setFirstHover(true)}} 
          onMouseLeave={() => {setFirstHover(false)}}
          className="first-card card" >
            <div className="card-top">
              <motion.div 
                initial={{y: 250, opacity: 0.5, rotate: 0}}
                animate= {firstHover ? {x: 100, rotate: '50deg', opacity: 1, scale: 1.3} : {x: 0, opacity: 0.5, rotate: '0deg'}}
                transition={{duration: 0.2}}
                className="first-acc acc">
              </motion.div>
              <motion.div 
                initial= {{y: 170, x: 0}}
                animate= {firstHover ? {y: 150, x: -100, rotate: '-50deg', opacity: 1, scale: 1.3} : {x: 0, opacity: 0.5, rotate: '0deg'}}
                transition={{duration: 0.2}}
                className="second-acc acc">
              </motion.div>
              <motion.div 
                initial= {{y: 90, x: 0}}
                animate= {firstHover ? {y: 50, x: 100, rotate: '50deg', opacity: 1, scale: 1.3} : {x: 0, opacity: 0.5, rotate: '0deg'}}
                transition={{duration: 0.2}}
                className="third-acc acc">
              </motion.div>
              <motion.div 
                animate= {firstHover ? {rotate: '3deg', y: -20, scale: 1.1}: {}}
                transition={{duration: 0.2}}
                className="image">
                <Image src={images.Smoothe1}/>
              </motion.div>
            </div>
            <motion.div
              animate= {firstHover ? {scale: 0.9}: {}} 
              transition={{duration: 0.2}}
              className="bgc">  
            </motion.div>
            <motion.div className="buttons">
              <motion.button                 
                animate= {firstHover ? {y: 0}: {y: 15}}
                transition={{duration: 0.2, delay: 0.1}}
                className="first-button">Shop Now</motion.button>
              <motion.button                 
                animate= {firstHover ? {y: 0}: {y: 15}}
                transition={{duration: 0.2, delay: 0.1}}
                className="second-button"><div>+</div></motion.button>
            </motion.div>
          </div>

          <div             
            onMouseEnter={() => {setSecondHover(true)}} 
            onMouseLeave={() => {setSecondHover(false)}}
            className="second-card card">
          <div className="card-top">
              <motion.div 
                initial={{y: 250, opacity: 0.5, rotate: 0}}
                animate= {secondHover ? {x: 100, rotate: '50deg', opacity: 1, scale: 1.3} : {x: 0, opacity: 0.5, rotate: '0deg'}}
                transition={{duration: 0.2}}
                className="first-acc acc">
              </motion.div>
              <motion.div 
                initial= {{y: 170, x: 0}}
                animate= {secondHover ? {y: 150, x: -100, rotate: '-50deg', opacity: 1, scale: 1.3} : {x: 0, opacity: 0.5, rotate: '0deg'}}
                transition={{duration: 0.2}}
                className="second-acc acc">
              </motion.div>
              <motion.div 
                initial= {{y: 90, x: 0}}
                animate= {secondHover ? {y: 50, x: 100, rotate: '50deg', opacity: 1, scale: 1.3} : {x: 0, opacity: 0.5, rotate: '0deg'}}
                transition={{duration: 0.2}}
                className="third-acc acc">
              </motion.div>
              <motion.div 
                animate= {secondHover ? {rotate: '3deg', y: -20, scale: 1.1}: {}}
                transition={{duration: 0.2}}
                className="image">
                <Image src={images.Smoothe2}/>
              </motion.div>
            </div>
            <motion.div
              animate= {secondHover ? {scale: 0.9}: {}} 
              transition={{duration: 0.2}}
              className="bgc">  
            </motion.div>
            <motion.div className="buttons">
              <motion.button                 
                animate= {secondHover ? {y: 0}: {y: 15}}
                transition={{duration: 0.2, delay: 0.1}}
                className="first-button">Shop Now</motion.button>
              <motion.button                 
                animate= {secondHover ? {y: 0}: {y: 15}}
                transition={{duration: 0.2, delay: 0.1}}
                className="second-button"><div>+</div></motion.button>
            </motion.div>
          </div>

          <div             
            onMouseEnter={() => {setThirdHover(true)}} 
            onMouseLeave={() => {setThirdHover(false)}}
            className="third-card card">
          <div className="card-top">
              <motion.div 
                initial={{y: 250, opacity: 0.5, rotate: 0}}
                animate= {thirdHover ? {x: 100, rotate: '50deg', opacity: 1, scale: 1.3} : {x: 0, opacity: 0.5, rotate: '0deg'}}
                transition={{duration: 0.2}}
                className="first-acc acc">
              </motion.div>
              <motion.div 
                initial= {{y: 170, x: 0}}
                animate= {thirdHover ? {y: 150, x: -100, rotate: '-50deg', opacity: 1, scale: 1.3} : {x: 0, opacity: 0.5, rotate: '0deg'}}
                transition={{duration: 0.2}}
                className="second-acc acc">
              </motion.div>
              <motion.div 
                initial= {{y: 90, x: 0}}
                animate= {thirdHover ? {y: 50, x: 100, rotate: '50deg', opacity: 1, scale: 1.3} : {x: 0, opacity: 0.5, rotate: '0deg'}}
                transition={{duration: 0.2}}
                className="third-acc acc">
              </motion.div>
              <motion.div 
                animate= {thirdHover ? {rotate: '3deg', y: -20, scale: 1.1}: {}}
                transition={{duration: 0.2}}
                className="image">
                <Image src={images.Smoothe4}/>
              </motion.div>
            </div>
            <motion.div
              animate= {thirdHover ? {scale: 0.9}: {}} 
              transition={{duration: 0.2}}
              className="bgc">  
            </motion.div>
            <motion.div className="buttons">
              <motion.button                 
                animate= {thirdHover ? {y: 0}: {y: 15}}
                transition={{duration: 0.2, delay: 0.1}}
                className="first-button">Shop Now</motion.button>
              <motion.button                 
                animate= {thirdHover ? {y: 0}: {y: 15}}
                transition={{duration: 0.2, delay: 0.1}}
                className="second-button"><div>+</div></motion.button>
            </motion.div>
          </div>
          
        </div>
      </main>

    </>
  );
}
