import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import images from "@/asset";
import { delay, motion } from "framer-motion";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });


const Ab = ({children}) => {
  return (
    <motion.div
    initial= {{opacity: 0, scale: 0, y: 0}}
    whileInView= {{opacity: 1, scale: 1, y: [200, 0]}}
    viewport={{once: true}}
  >
    {children}
  </motion.div>
  )
}

export default function Home() {
  const [firstHover, setFirstHover] = useState(false);
  const [secondHover, setSecondHover] = useState(false);
  const [thirdHover, setThirdHover] = useState(false);
  const [packHover, setPackHover] = useState(false);  


  console.log(packHover);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </Head>
      <main>

        <div className="left_absolute">
            <Ab>
              <motion.div className="first_left"            
              animate={{rotate: -360}}
              transition={{duration: 10, ease: "linear", repeat: Infinity}}
            >
                <Image src={images.Berry2}/>
              </motion.div>
            </Ab>


            <Ab>
              <motion.div className="second_left"
              initial= {{opacity: 0, scale: 0}}
              whileInView={{opacity: [0,1], scale: [0, 1], rotate: ['50deg', '20deg'], y: -100}}
            >
                <Image src={images.Watermelon}/>              
              </motion.div>
            </Ab>


            <Ab>
              <motion.div className="third_left" 
                animate={{y: [0, -15, 0], rotate: ['-12deg', '-10deg', '-12deg']}}
                transition={{duration: 6, ease: "easeInOut", repeat: Infinity}}
              >
                <Image src={images.Strawberry}/>
              </motion.div>
            </Ab>


            <Ab>
              <motion.div className="fourth_left" 
                animate={{y: [0, -15, 0], rotate: ['50deg', '40deg', '50deg']}}
                transition={{duration: 6, ease: "easeInOut", repeat: Infinity}}
              >
                <Image src={images.Mango3}/>
              </motion.div>
            </Ab>


            <Ab>
              <motion.div className="fifth_left" 
                animate={{y: [0, -15, 0], rotate: ['-30deg', '-28deg', '-30deg']}}
                transition={{duration: 6, ease: "easeInOut", repeat: Infinity}}
              >
                <Image src={images.KaleLeaf}/>
              </motion.div>
            </Ab>


            <Ab>
              <motion.div className="sixth_left" 
                animate={{y: [0, -15, 0], rotate: ['140deg', '142deg', '140deg']}}
                transition={{duration: 6, ease: "easeInOut", repeat: Infinity}}
              >
                <Image src={images.Watermelon}/>
              </motion.div>
            </Ab>

          


        </div>

        <div className="right_absolute">
            <Ab>
              <motion.div className="first_right"
                animate={{y: [-15, 0, -15]}}
                transition={{duration: 6, ease: "easeInOut", repeat: Infinity}}
              >
                <Image src={images.Mango2}/>
              </motion.div>
            </Ab>

            <Ab>
              <motion.div className="second_right"
                animate={{rotate: 360}}
                transition={{duration: 20, ease: "easeInOut", repeat: Infinity}}
              
              >
                <Image src={images.Berry1}/>
              </motion.div>  
            </Ab> 


            <Ab>
              <motion.div className="third_right"
              animate={{y: [-15, 0, -15], rotate: ['90deg', '90deg']}}
              transition={{duration: 6, ease: "easeInOut", repeat: Infinity}}                 
            >
                <Image src={images.Chocolate2}/>
              </motion.div>
            </Ab>


            <Ab>
              <motion.div className="fourth_right"
              animate={{rotate: 360}}
              transition={{duration: 20, ease: "easeInOut", repeat: Infinity}}
            >
                <Image src={images.Berry2}/>
              </motion.div>
            </Ab>

            
            <Ab>
              <motion.div className="fifth_right"
              animate={{rotate: -360}}
              transition={{duration: 40, ease: "easeInOut", repeat: Infinity}}
            >
                <Image src={images.Berry2}/>
              </motion.div>
            </Ab>


            <Ab>
              <motion.div className="sixth_right"
                animate={{y: [-25, -50, -25], rotate: ['-30deg', '-35deg', '-30deg']}}
                transition={{duration: 6, ease: "easeInOut", repeat: Infinity}}      
            >
                <Image src={images.Watermelon}/>
              </motion.div>
            </Ab>


            <Ab>
              <motion.div className="seventh_right"
                animate={{y: [-25, -40, -25], rotate: ['-30deg', '-32deg', '-30deg']}}
                transition={{duration: 5, ease: "easeInOut", repeat: Infinity}}      
            >
                <Image src={images.Chocolate2}/>
              </motion.div>
            </Ab>


            <Ab>
              <motion.div className="eighth_right"
                animate={{y: [-25, -15, -25], rotate: ['0deg', '3deg', '0deg']}}
                transition={{duration: 8, ease: "easeInOut", repeat: Infinity}}      
            >
                <Image src={images.Berry1}/>
              </motion.div>
            </Ab>



        </div>


        <nav>
            <button className="shop">Shop</button>
            <button className="meet">Meet Smoothe</button>
            <div className="logo">Smoothe</div>
            <div className="margin"></div>
            <div className="kart">kart</div>
        </nav>


        <div className="header">
          <div className="header-content">
            <div className="header-left">
              <h1>A Better Smoothie is Here</h1>
              <h2>Delicious smoothies without any of the prep. Made with real fruits & veggies plus plant protein!</h2>
              <motion.button
              whileHover={{scale: 1.1}}
              >Shop Now </motion.button>
            </div>
            <div className="header-right">
              <motion.div className="header-star"
                animate={{rotate: '360deg'}}
                transition={{duration: 60,repeat: Infinity, ease: 'linear'}}
                >
                <Image src={images.Star}/>
              </motion.div>
              <div className="header-image">
                <motion.div 
                initial={{scale: 0.9, x: 170, y: 20, rotate: '16deg'}}   
                animate={{y:[0, 20, 0]}}
                transition={{duration: 6, repeat: Infinity, ease: 'easeInOut'}}
                className="image-1">
                  <Image src={images.Smoothe1} />
                </motion.div>
                <motion.div 
                initial={{scale: 0.95, x: -170, y: -20, rotate: '-12deg'}}       
                animate={{y:[-20, 0, -20], x:[-180, -170, -180], rotate:['-12deg', '-10deg', '-12deg']}}
                transition={{duration: 6, repeat: Infinity, type: "easeInOut"}}         
                className="image-2">
                  <Image src={images.Smoothe2} />
                </motion.div>
                <motion.div     
                animate={{y:[0, -20, 0], rotate:['0deg', '2deg', '0deg']}}
                transition={{duration: 6, repeat: Infinity, type: "easeInOut"}}                    
                className="image-3">
                  <Image src={images.Smoothe4} />
                </motion.div>
              </div>
            </div>
          </div>
        </div>


        <div className="gradient"></div>


        <div className="servings">
          <motion.div className="servings_content"       
          >

            <h2 className="servings_heading">3 SERVINGS OF FRUITS & VEGGIES</h2>
            <div className="servings_para_container">
              <p className="servings_para">NO FILLERS.<br/>
                NO PRESERVATIVES.<br/>
                NO ARTIFICIAL ANYTHING.<br/>
                JUST FRESH-FROM-THE-BLENDER DELICIOUSNESS, BOTTLED UP & READY TO GO!</p>
              <div className="servings_SVG_container"
              >
                <motion.svg 
                animate= {{rotate: [30, 0, 30]}}
                transition={{duration: '8', repeat: Infinity, ease: 'easeInOut'}}                
                id="Layer_1" data-name="Layer 1" version="1.1" viewBox="0 0 325.37 310.9">
                  <path fill="#77dbfc" class="cls-1" d="M169.98,19.73l29.33-14.34c8.05-3.93,17.76-.78,21.96,7.13l15.3,28.84c2.4,4.52,6.75,7.69,11.8,8.57l32.15,5.64c8.82,1.55,14.82,9.81,13.57,18.68l-4.57,32.32c-.72,5.07.95,10.19,4.51,13.87l22.7,23.46c6.23,6.44,6.23,16.65,0,23.09l-22.7,23.46c-3.56,3.68-5.22,8.8-4.51,13.87l4.57,32.32c1.25,8.87-4.75,17.13-13.57,18.68l-32.15,5.64c-5.04.88-9.4,4.05-11.8,8.57l-15.3,28.84c-4.2,7.91-13.91,11.07-21.96,7.13l-29.33-14.34c-4.6-2.25-9.98-2.25-14.58,0l-29.33,14.34c-8.05,3.93-17.76.78-21.96-7.13l-15.3-28.84c-2.4-4.52-6.75-7.69-11.8-8.57l-32.15-5.64c-8.82-1.55-14.82-9.81-13.57-18.68l4.57-32.32c.72-5.07-.95-10.19-4.51-13.87l-22.7-23.46c-6.23-6.44-6.23-16.65,0-23.09l22.7-23.46c3.56-3.68,5.22-8.8,4.51-13.87l-4.57-32.32c-1.25-8.87,4.75-17.13,13.57-18.68l32.15-5.64c5.04-.88,9.4-4.05,11.8-8.57l15.3-28.84c4.2-7.91,13.91-11.07,21.96-7.13l29.33,14.34c4.6,2.25,9.98,2.25,14.58,0Z"/>
                </motion.svg>
              </div>
            </div>
            <div className="nutritional_content">
                <Image src={images.Sugar}/>
                <Image src={images.Protein}/>
                <Image src={images.Fiber}/>
            </div>
          </motion.div>
        </div>

        <div className="shop-sec">

          <div             
              onMouseEnter={() => {setFirstHover(true)}} 
              onMouseLeave={() => {setFirstHover(false)}}
              className="first-card card">
            <div className="card-top">
                <motion.div 
                  initial={{y: 300, opacity: 0.5, scale: 0.2, x: 0}}
                  animate= {firstHover ? {x: 120, y: 270, rotate: '50deg', opacity: 1, scale: 2} : {}}
                  transition={{duration: 0.3}}
                  className="first-acc acc">
                  <Image src={images.Watermelon} />
                </motion.div>
                <motion.div 
                  initial= {{y: 300, opacity: 0.5, scale: 0.2, x: 0, rotate: '-50deg'}}
                  animate= {firstHover ? {y: 150, x: -140, rotate: '-70deg', opacity: 1, scale: 1.7} : {}}
                  transition={{duration: 0.3}}
                  className="second-acc acc">
                  <Image src={images.Strawberry} />
                </motion.div>
                <motion.div 
                  initial= {{y: 300, opacity: 0.5, scale: 0.2, x: 0}}
                  animate= {firstHover ? {y: 50, x: 100, rotate: '0deg', opacity: 1, scale: 1.3} : {}}
                  transition={{duration: 0.3}}
                  className="third-acc acc">
                  <Image src={images.Strawberry} />
                </motion.div>
                <motion.div 
                  animate= {firstHover ? {rotate: '3deg', y: -40, scale: 1.1}: {}}
                  transition={{duration: 0.14}}
                  className="image">
                  <Image src={images.Smoothe1}/>
                </motion.div>
              </div>
              <motion.div
                animate= {firstHover ? {scale: 0.9}: {}} 
                transition={{duration: 0.2, delay: 0.08}}
                className="bgc">  
              </motion.div>
              <motion.div className="buttons">
                <motion.button                 
                  animate= {firstHover ? {y: 0}: {y: 15}}
                  transition={{duration: 0.2, delay: 0.1}}
                  className="first-button">Shop Now</motion.button>
                <motion.button                 
                  animate= {firstHover ? {y: 0}: {y: 15}}
                  transition={{duration: 0.2, delay: 0.1}}
                  className="second-button"><div>+</div></motion.button>
              </motion.div>
          </div>

          <div             
              onMouseEnter={() => {setSecondHover(true)}} 
              onMouseLeave={() => {setSecondHover(false)}}
              className="second-card card">
            <div className="card-top">
                <motion.div 
                  initial={{y: 300, opacity: 0.5, scale: 0.2, x: 0}}
                  animate= {secondHover ? {x: 120, y: 270, rotate: '50deg', opacity: 1, scale: 1.3} : {}}
                  transition={{duration: 0.3}}
                  className="first-acc acc">
                  <Image src={images.Banana2} />
                </motion.div>
                <motion.div 
                  initial= {{y: 300, opacity: 0.5, scale: 0.2, x: 0}}
                  animate= {secondHover ? {y: 150, x: -140, rotate: '-20deg', opacity: 1, scale: 1.7} : {}}
                  transition={{duration: 0.3}}
                  className="second-acc acc">
                  <Image src={images.Chocolate2} />
                </motion.div>
                <motion.div 
                  initial= {{y: 300, opacity: 0.5, scale: 0.2, x: 0}}
                  animate= {secondHover ? {y: 50, x: 100, rotate: '30deg', opacity: 1, scale: 1.3} : {}}
                  transition={{duration: 0.3}}
                  className="third-acc acc">
                  <Image src={images.Chocolate3} />
                </motion.div>
                <motion.div 
                  animate= {secondHover ? {rotate: '3deg', y: -40, scale: 1.1}: {}}
                  transition={{duration: 0.14}}
                  className="image">
                  <Image src={images.Smoothe2}/>
                </motion.div>
              </div>
              <motion.div
                animate= {secondHover ? {scale: 0.9}: {}} 
                transition={{duration: 0.2, delay: 0.08}}
                className="bgc">  
              </motion.div>
              <motion.div className="buttons">
                <motion.button                 
                  animate= {secondHover ? {y: 0}: {y: 15}}
                  transition={{duration: 0.2, delay: 0.1}}
                  className="first-button">Shop Now</motion.button>
                <motion.button                 
                  animate= {secondHover ? {y: 0}: {y: 15}}
                  transition={{duration: 0.2, delay: 0.1}}
                  className="second-button"><div>+</div></motion.button>
              </motion.div>
          </div>

          <div             
              onMouseEnter={() => {setThirdHover(true)}} 
              onMouseLeave={() => {setThirdHover(false)}}
              className="third-card card">
            <div className="card-top">
                <motion.div 
                  initial={{y: 300, opacity: 0.5, scale: 0.2, x: 0}}
                  animate= {thirdHover ? {x: 120, y: 270, rotate: '70deg', opacity: 1, scale: 1.3} : {}}
                  transition={{duration: 0.3}}
                  className="first-acc acc">
                  <Image src={images.Berry1} />
                </motion.div>
                <motion.div 
                  initial= {{y: 300, opacity: 0.5, scale: 0.2, x: 0}}
                  animate= {thirdHover ? {y: 150, x: -140, rotate: '-20deg', opacity: 1, scale: 1.3} : {}}
                  transition={{duration: 0.3}}
                  className="second-acc acc">
                  <Image src={images.Berry2} />
                </motion.div>
                <motion.div 
                  initial= {{y: 300, opacity: 0.5, scale: 0.2, x: 0}}
                  animate= {thirdHover ? {y: 50, x: 130, rotate: '-30deg', opacity: 1, scale: 1.7} : {}}
                  transition={{duration: 0.3}}
                  className="third-acc acc">
                  <Image src={images.KaleLeaf} />
                </motion.div>
                <motion.div 
                  animate= {thirdHover ? {rotate: '3deg', y: -40, scale: 1.1}: {}}
                  transition={{duration: 0.14}}
                  className="image">
                  <Image src={images.Smoothe4}/>
                </motion.div>
              </div>
              <motion.div
                animate= {thirdHover ? {scale: 0.9}: {}} 
                transition={{duration: 0.2, delay: 0.08}}
                className="bgc">  
              </motion.div>
              <motion.div className="buttons">
                <motion.button                 
                  animate= {thirdHover ? {y: 0}: {y: 15}}
                  transition={{duration: 0.2, delay: 0.1}}
                  className="first-button">Shop Now</motion.button>
                <motion.button                 
                  animate= {thirdHover ? {y: 0}: {y: 15}}
                  transition={{duration: 0.2, delay: 0.1}}
                  className="second-button"><div>+</div></motion.button>
              </motion.div>
          </div>
          
        </div>       

        <div className="variety-pack">
          <div className="pack-container"
              onMouseEnter={() => setPackHover(true)} 
              onMouseLeave={() => setPackHover(false)}>
            <div className="pack-bg">
              <motion.div
                animate= {packHover ? {height: '90%'}: {}} 
                transition={{duration: 0.15}}
              ></motion.div>
              </div>
            <div className="pack-top">
              <div className="pack-left">
                <h2>VARIETY PACK</h2>
                <p>All of our delicious flavors in one handy box. Includes two each of our Greenfest, Very Berry, and Choconana smoothies.</p>
              </div>
              <div className="pack-right">
                <motion.div className="pack-first-image pack-image"
                  animate= {packHover ? {scale: 1.1, rotate: '-10deg', x: -30, y: -20} : {}}
                >
                  <Image src={images.Smoothe1}/>
                </motion.div>
                <motion.div className="pack-second-image pack-image"
                  animate= {packHover ? {scale: 1.2, rotate: '3deg', x: 0, y: 20} : {}}
                >
                  <Image src={images.Smoothe2}/>
                </motion.div>
                <motion.div className="pack-third-image pack-image"
                  animate= {packHover ? {scale: 1, rotate: '10deg', x: 20, y: -10} : {}}
                >
                  <Image src={images.Smoothe4}/>
                </motion.div>
              </div>
            </div>
            <div className="pack-bottom">
              <motion.button
                animate={packHover ? {y: -5} : {y: '0.7rem'}}
                transition={{delay: 0.1}}
              ><div>+</div></motion.button>
              <motion.button
              
              animate={packHover ? {y: -5} : {y: '0.7rem'}}
              transition={{delay: 0.1}}>SHOP NOW</motion.button>
            </div>
          </div>
        </div>


        <div className="margin_green"></div>


        <div className="philosophy">
          <div className="philosophy_content">
            <div className="philosophy_para_container">
              <p className="philosophy_para">DID YOU KNOW ONLY 1 IN <br/> 10 ADULTS EATS THE <br/> RECOMMENDED DAILY <br/> SERVING OF FRUITS & <br/> VEGGIES?</p>
              <div className="philosophy_SVG_container"
              >
                <motion.svg 
                animate= {{rotate: [30, 0, 30]}}
                transition={{duration: '8', repeat: Infinity, ease: 'easeInOut'}}                
                id="Layer_1" data-name="Layer 1" version="1.1" viewBox="0 0 325.37 310.9">
                  <path fill="#ff9000" class="cls-1" d="M169.98,19.73l29.33-14.34c8.05-3.93,17.76-.78,21.96,7.13l15.3,28.84c2.4,4.52,6.75,7.69,11.8,8.57l32.15,5.64c8.82,1.55,14.82,9.81,13.57,18.68l-4.57,32.32c-.72,5.07.95,10.19,4.51,13.87l22.7,23.46c6.23,6.44,6.23,16.65,0,23.09l-22.7,23.46c-3.56,3.68-5.22,8.8-4.51,13.87l4.57,32.32c1.25,8.87-4.75,17.13-13.57,18.68l-32.15,5.64c-5.04.88-9.4,4.05-11.8,8.57l-15.3,28.84c-4.2,7.91-13.91,11.07-21.96,7.13l-29.33-14.34c-4.6-2.25-9.98-2.25-14.58,0l-29.33,14.34c-8.05,3.93-17.76.78-21.96-7.13l-15.3-28.84c-2.4-4.52-6.75-7.69-11.8-8.57l-32.15-5.64c-8.82-1.55-14.82-9.81-13.57-18.68l4.57-32.32c.72-5.07-.95-10.19-4.51-13.87l-22.7-23.46c-6.23-6.44-6.23-16.65,0-23.09l22.7-23.46c3.56-3.68,5.22-8.8,4.51-13.87l-4.57-32.32c-1.25-8.87,4.75-17.13,13.57-18.68l32.15-5.64c5.04-.88,9.4-4.05,11.8-8.57l15.3-28.84c4.2-7.91,13.91-11.07,21.96-7.13l29.33,14.34c4.6,2.25,9.98,2.25,14.58,0Z"/>
                </motion.svg>
              </div>
            </div>
            <h2 className="philosophy_heading">OUR PHILOSOPHY</h2>
            <p className="philosophy_para-2">
            We all want to eat healthier, but far too often our busy lives get in the way. At Smoothe, we’re making healthy living second nature. Our fruit & veggie smoothies taste deliciously fresh, require zero prep, and can go with you anywhere!
            </p>
            <button>MEET SMOOTHIE</button>
          </div>
        </div>

        <footer>
          <div className="footer_first">
            <h2>STAY IN THE LOOP</h2>
          </div>
          <div className="footer_second">
            <input type="mail" placeholder="Enter Your Mail"></input>
            <a>SUBMIT</a>
          </div>
          <div className="footer_third">
            <div>SHOP</div>
            <div>ABOUT</div>
            <div>SUPPORT</div>
          </div>
        </footer>

      </main>

    </>
  );
}
